accounts/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
               path('contact/', views.ContactView.as_view(), name='contact'),
               path('signup/', views.SignUpView.as_view(), name='signup'),
               path('profile/', views.profile_view, name='profile'),
               path('profile/edit/', views.ProfileUpdate.as_view(),
                    name='edit'),
               path('logout/', views.logout_view, name='logout'),
               path('login/',
                    auth_views.LoginView.as_view(
                        template_name='accounts/login.html'), name='login')
              ]

letsplay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('sports_centre.urls')),
	# path('',include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sports_centre/urls.py
from django.urls import path

from . import views

app_name = 'sports_centre'

urlpatterns = [
               path('sports-centre/create/',
                    views.CreateGroundView.as_view(), name='create'),
               path('', views.HomeView.as_view(), name='home'),
               path('sports-centre/<int:pk>/',
                    views.SportsCentreDetailView.as_view(), name='detail'),
               path('sports-centre/<int:pk>/edit/',
                    views.EditGroundView.as_view(), name='edit'),
               path('sports-centre/<int:pk>/delete/',
                    views.DeleteGroundView.as_view(), name='delete'),
               path('sports-centre/<int:pk>/book/',
                    views.BookingView.as_view(), name='book'),
               path('sports-centre/booking-list/',
                    views.BookingListing.as_view(), name='booking-list'),
              ]

accounts/models.py
from django.db import models

# Create your models here.

sports_centre/models.py
from django.contrib.auth.models import User
from django.db import models


class SportsCentre(models.Model):
    """SportsCentre having image"""
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=250)
    address = models.TextField(max_length=250)
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.FileField()

    def __str__(self):
        return self.name


class Booking(models.Model):
    """Booking object related to SportsCentre."""
    name = models.CharField(max_length=200)
    sports_centre = models.ForeignKey(SportsCentre, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)
    date = models.DateField()
    slot = models.CharField(max_length=100)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class BootstrapMixinForm(forms.ModelForm):
    """
    Sample Django Form To add Bootstrap's Form Control class to every field.
    """
    def __init__(self, *args, **kwargs):
        super(BootstrapMixinForm, self).__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

    class Meta:
        abstract = True


class UserForm(BootstrapMixinForm):
    """Signup Form"""
    password = forms.CharField(widget=forms.PasswordInput,
                               help_text="*Required")
    email = forms.EmailField(required=True, help_text="*Required")
    username = forms.CharField(help_text="*Required")

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']


class ProfileForm(BootstrapMixinForm):
    """Edit Profile Form."""
    email = forms.EmailField(required=True, help_text="*Required")

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class ContactForm(forms.Form):
    """Contact Form."""
    name = forms.CharField(label="Enter your name:", required=True,
                           help_text="*Required")
    phone_number = forms.CharField(label="Enter phone number:", required=False)
    email = forms.EmailField(label="Enter email:", required=True,
                             help_text="*Required")
    feedback = forms.CharField(widget=forms.Textarea, label="Enter Feedback:",
                               required=True, help_text="*Required")

accounts/views.py
"""
Accounts Views.
"""
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import ContactForm, ProfileForm, UserForm


class SignUpView(View):
    """Show the signup page."""
    form_class = UserForm
    template_name = 'accounts/signup.html'

    def get(self, request):
        """
        Renders the UserForm in template specified in template_name.
        """
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """Save the user object in the model."""
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('accounts:profile')

        return render(request, self.template_name, {'form': form})


@login_required(login_url='accounts:login')
def profile_view(request):
    """Profile Page with user details."""
    template_name = 'accounts/profile.html'
    return render(request, template_name)


def logout_view(request):
    """Logout the current user."""
    logout(request)

    return redirect('sports_centre:home')


class ProfileUpdate(LoginRequiredMixin, View):
    """
    Edit the Profile details of current user.
    """
    login_url = 'accounts:login'
    form_class = ProfileForm
    template_name = "accounts/update.html"
    # success_url = 'accounts:profile'

    def get(self, request):
        """Render the form to the template."""
        form = self.form_class(instance=request.user)
        return render(request, self.template_name, {'form': form}, )

    def post(self, request):
        """Save the changes and redirect to profile page."""
        form = self.form_class(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile")


class ContactView(View):
    """ Contact Page."""
    form_class = ContactForm
    template_name = 'accounts/contact.html'

    def get(self, request):
        """Show the Contact Page."""
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """Send email notification to both admin and customer."""
        form = self.form_class(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone_number']
            email = form.cleaned_data['email']
            feedback = form.cleaned_data['feedback']

            subject = "Let's Play:Feedback"
            from_email = settings.EMAIL_HOST_USER
            to_email = [email]
            message = ("Hi "+name+",\nThank you for your feedback.\nRegards," +
                       "\nLet's Play")

            send_mail(subject, message, from_email, to_email,
                      fail_silently=False,)
            to_email = [settings.EMAIL_HOST_USER]
            message = ("Hi Admin,\nName:"+name+"\nPhone Number:"+phone +
                       "\nEmail: "+email+"\nFeedback:"+feedback+"\nthank you")

            send_mail(subject, message, from_email, to_email,
                      fail_silently=False,)
            success_message = "Thank you for your valuable feedback "+name+"!!"
            messages.success(request, success_message)
            return HttpResponseRedirect(reverse_lazy('accounts:contact'))

        return render(request, self.template_name, {'form': form})

accounts/templates/accounts/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title_text%}{% endblock%}|Let'sPlay</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Great+Vibes" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}"> 
</head>
<body>
<!--Navbar start -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href="{% url 'sports_centre:home' %}" id="logo">Let'sPlay</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                {%block searchbar%}
                {%endblock%}
                <li class="{%block home_class%}{%endblock%}"><a href="{% url 'sports_centre:home' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>                
                <li class="{%block contact_class%}{%endblock%}"><a href="{% url 'accounts:contact' %}"><span class="glyphicon glyphicon-envelope"></span>&nbsp;Contact Us</a></li>
                {% if request.user.is_authenticated %}
                <li title="Click to enter Profile">
                    <a href="{% url 'accounts:profile' %}">
                        <span class="glyphicon glyphicon-user"></span>&nbsp;{{user.username}}
                    </a>
                </li>
                <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-off"></span>&nbsp;Logout</a></li>
                {% else %}
                <li class="{%block signup_class%}{%endblock%}"><a href="{% url 'accounts:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li class="{%block login_class%}{%endblock%}"><a href="{% url 'accounts:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>  
    </div>
</nav>
<!--Navbar end -->


<!--All the contents will come inside this!!!-->    
{% block content %}

{%endblock%}  




<!--Footer starts here-->
<div class="container-fluid footer">  
    <div class="container">  
        <div class="row">
            <div class="col-sm-4">
                <h3>Latest Posts</h3>                       
                <div class="post">
                    <h4><a href=""><strong>Lorem ipsum dolor sit amet.</strong></a></h4>                
                    Lorem ipsum dolor sit amet, consectetur                             
                </div>
                <div class="post">
                    <h4><a href=""><strong>Lorem ipsum dolor sit amet.</strong></a></h4>                
                    Lorem ipsum dolor sit amet, consectetur                             
                </div>
                <div class="post">
                    <h4><a href=""><strong>Lorem ipsum dolor sit amet.</strong></a></h4>                
                    Lorem ipsum dolor sit amet, consectetur                             
                </div>
            </div>
            <div class="col-sm-4">
                <h3>About</h3>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Hic incidunt, quis voluptatum nostrum, sit iusto perferendis 
                qui consequuntur numquam, earum impedit. Iste cumque porro, 
                debitis aperiam asperiores cum repellat voluptatem.
            </div>
            <div class="col-sm-4">
                <h3>Stay Connected</h3>                             
                <div class="link">
                    <a href="https://www.facebook.com/">
                    <img src="{% static 'accounts/images/facebook.png' %}" alt="facebook" target="_blank">&nbsp; Facebook<br>
                    </a>
                    <br>
                </div>
                <div class="link">
                    <a href="https://twitter.com/">
                    <img src="{% static 'accounts/images/twitter.png'%}" alt="twitter" target="_blank">&nbsp; Twitter<br>
                    </a>
                    <br>
                </div>
                <div class="link">
                    <a href="https://www.rss.com/">
                    <img src="{% static 'accounts/images/rss.png'%}" alt="RSS" target="_blank">&nbsp; RSS <br>
                    </a>
                    <br>
                </div>
                <div class="link">
                    <a href="https://plus.google.com/discover">
                    <img src="{% static 'accounts/images/googleplus.png'%}" alt="googleplus" target="_blank">&nbsp; Google+<br>
                    </a>
                    <br>
                </div>      
            </div>
        </div>
    </div>
</div>
<!--Footer ends here-->

<script src="{% static 'accounts/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'accounts/bootstrap/js/bootstrap.min.js' %}"></script>
<!--<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
       rel = "stylesheet">
<script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>-->
<!--
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script> -->

{%block js%}

{% endblock%}
<script type="text/javascript" charset="utf-8" async defer>
$(function() {
  // $( "#id_date" ).datepicker({dateFormat: "yy-mm-dd"});
  // $("#id_username").addClass('form-control');
  $('input').addClass('form-control');
  $('textarea').addClass('form-control');
  $('#id_image').removeClass('form-control');
  $('#id_image').addClass('form-control-file');

});
 

</script>
</body>
</html>

accounts/templates/accounts/contact.html
{%extends "accounts/base.html"%}

{% block title_text%}Contact Us{% endblock%}

{%block contact_class%}active{%endblock%}
{%block content%}

<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Contact Us</strong></h1></div>
				<div class="panel-body">
					<div class="form-group">
						{% if messages %}
						    {% for message in messages %}			    
						    	<div class="alert alert-success">
						    		<strong>
						    			{{ message}}
						    		</strong>
						    	</div>		
						    {% endfor %}
						{% endif %}
					</div>
					<form method="post">
						{% csrf_token %}
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}						
						
						<input type="submit" class="btn btn-success" value="Submit"/>
					</form>
					<br>
					
				</div>
			</div>
		</div>
	</div>
</div>

{%endblock%}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block title_text%}Login{% endblock%}

{%block login_class%}active{%endblock%}
{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Login</strong></h1></div>
				<div class="panel-body">
					<form method="post" action="{% url 'accounts:login' %}">
						{% csrf_token %}
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}
						{% if form.errors %}
							<p class="error_message">Your username and password didn't match. Please try again.</p>
						{% endif %}
						<input type="submit" class="btn btn-success"value="Login" />
						<input type="hidden" name="next" value="{% url 'accounts:profile'%}" />
					</form>
					<br>
					<p>Not registered ?<a href="{% url 'accounts:signup' %}">Create an Account</a></p>	
				</div>
			</div>
		</div>
	</div>
</div>
{%endblock%}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% block title_text%}Profile{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-12 ">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Hi!! {{user.username}}</strong></h1></div>
				<div class="panel-body">
					{% block profilecontent%}	
					<h1>Profile Details</h1>
					<h4>Email: {{user.email}}</h4>
					<h4>Firstname: {{user.first_name}}</h4>
					<h4>LastName: {{user.last_name}}</h4>
					<br>
					{%if user.is_staff%}
					<a href="{% url 'sports_centre:create' %}" class="btn btn-warning btn-lg">Create Sports Centre</a>
					<a href="{% url 'sports_centre:booking-list' %}" class="btn btn-success btn-lg">Show Bookings</a>
					{%endif%}
					<a href="{% url 'accounts:edit' %}" class="btn btn-primary btn-lg">Edit Profile</a>
					{% endblock %}
				</div>
			</div>
		</div>
	</div>
</div>
{%endblock%}

accounts/templates/accounts/signup.html
{%extends "accounts/base.html"%}

{% block title_text%}SignUp{% endblock%}

{%block signup_class%}active{%endblock%}
{%block content%}

<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>SignUp</strong></h1></div>
				<div class="panel-body">
					<form method="post">
						{% csrf_token %}
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}						
						
						<input type="submit" class="btn btn-success" value="SignUp"/>
					</form>
					<br>
					<div class="signin">
						<p>Already a user ?<a href="{% url 'accounts:login' %}">Login</a></p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{%endblock%}

accounts/templates/accounts/update.html
{% extends "accounts/profile.html" %}

{% block title_text%}ProfileEdit{% endblock%}

{%block profilecontent%}

<form method="post">
	{% csrf_token %}
    {% for field in form %}
		<div class="form-group">
			{{ field.label_tag }}<br>
			{{ field }}
			<span class="helptext">{{field.help_text}}</span>
			<br>
		</div>
	{% endfor %}	
	<input type="submit" class="btn btn-success" value="Save"/>
    
</form>
<br>
<br>
<a href="{% url 'accounts:profile' %}" class="btn btn-primary ">Back to Profile</a>
{%endblock%}