accounts/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
               path('contact/', views.ContactView.as_view(), name='contact'),
               path('signup/', views.SignUpView.as_view(), name='signup'),
               path('profile/', views.profile_view, name='profile'),
               path('profile/edit/', views.ProfileUpdate.as_view(),
                    name='edit'),
               path('logout/', views.logout_view, name='logout'),
               path('login/',
                    auth_views.LoginView.as_view(
                        template_name='accounts/login.html'), name='login')
              ]

letsplay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('sports_centre.urls')),
	# path('',include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sports_centre/urls.py
from django.urls import path

from . import views

app_name = 'sports_centre'

urlpatterns = [
               path('sports-centre/create/',
                    views.CreateGroundView.as_view(), name='create'),
               path('', views.HomeView.as_view(), name='home'),
               path('sports-centre/<int:pk>/',
                    views.SportsCentreDetailView.as_view(), name='detail'),
               path('sports-centre/<int:pk>/edit/',
                    views.EditGroundView.as_view(), name='edit'),
               path('sports-centre/<int:pk>/delete/',
                    views.DeleteGroundView.as_view(), name='delete'),
               path('sports-centre/<int:pk>/book/',
                    views.BookingView.as_view(), name='book'),
               path('sports-centre/booking-list/',
                    views.BookingListing.as_view(), name='booking-list'),
              ]

sports_centre/models.py
from django.contrib.auth.models import User
from django.db import models


class SportsCentre(models.Model):
    """SportsCentre having image"""
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=250)
    address = models.TextField(max_length=250)
    opening_time = models.TimeField()
    closing_time = models.TimeField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.FileField()

    def __str__(self):
        return self.name


class Booking(models.Model):
    """Booking object related to SportsCentre."""
    name = models.CharField(max_length=200)
    sports_centre = models.ForeignKey(SportsCentre, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)
    date = models.DateField()
    slot = models.CharField(max_length=100)

    def __str__(self):
        return self.name

sports_centre/forms.py
from datetime import datetime, timedelta

from django import forms

from .models import Booking, SportsCentre


class BootstrapMixinForm(forms.ModelForm):
    """
    Sample Django Form To add Bootstrap's Form Control class to every field.
    """
    def __init__(self, *args, **kwargs):
        super(BootstrapMixinForm, self).__init__(*args, **kwargs)
        for myField in self.fields:
            self.fields[myField].widget.attrs['class'] = 'form-control'

    class Meta:
        abstract = True


class BookingForm(BootstrapMixinForm):
    """
    Booking form containing name,phone_number,date,slot.

    Multiple slots can be booked for a date.
    """
    slot = forms.MultipleChoiceField(widget=forms.SelectMultiple())

    class Meta:
        model = Booking
        fields = ['name', 'phone_number', 'date', 'slot']

    def __init__(self, id, *args, **kwargs):
        """
        id : id of the SportsCentre.

        Calls calc_choices function to create choices for slots.

        Label of the slot field is also defined.
        """
        super(BookingForm, self).__init__(*args, **kwargs)
        self.fields['slot'].choices = self.calc_choices(id)
        self.fields['slot'].label = "Select Slots Needed:"

    def calc_choices(self, id):
        """
        This function takes id of the SportsCentre as argument and
        returns the SLOT_CHOICES for the multiple select field.

        Time slot tuples are appended to SLOT_CHOICES.

        Each tuple is generated by looping from the opening time to the closing
        time of the particular SportsCentre with an interval of 1 hour.

        Since only datetime objects can be added with timedelta, a sample date
        of 2001-8-5 is used.
        """
        booking_centre = SportsCentre.objects.get(id=id)
        ao = booking_centre.opening_time
        ac = booking_centre.closing_time
        # the date provided below is just a sample date
        # it is used for iterating through the timing as datetime object
        start = datetime(2001, 8, 5, ao.hour, ao.minute)
        end = datetime(2001, 8, 5, ac.hour, ac.minute)

        SLOT_CHOICES = ()

        test = start
        while(test < end):
            display_string = (test.strftime("%I %M %p") + " to " +
                              (test+timedelta(hours=1)).strftime("%I %M %p"))
            timing_slot = (display_string, display_string)
            SLOT_CHOICES = SLOT_CHOICES+(timing_slot,)
            test = test+timedelta(hours=1)
        return SLOT_CHOICES

sports_centre/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import BookingForm
from .models import Booking, SportsCentre


class CreateGroundView(UserPassesTestMixin, CreateView):
    """
    Used to create a SportsCentre Object.

    Renders a form to the specified template_name on GET request.

    The Form will contain all the fields specified in the fields attribute.
    """
    login_url = 'sports_centre:home'
    model = SportsCentre
    fields = ['name', 'description', 'address',
              'opening_time', 'closing_time', 'image']
    template_name = 'sports_centre/create.html'
    success_url = reverse_lazy('sports_centre:home')

    def form_valid(self, form):
        """
        Add the currently logged-in user as creator and
        redirect to success_url if form is valid.
        """
        form.instance.creator = self.request.user
        return super().form_valid(form)

    def test_func(self):
        """
        Checks whether the user trying to access the url is a staff member,
        if not redirect to login_url.
        """
        return self.request.user.is_staff


class EditGroundView(UserPassesTestMixin, UpdateView):
    """
    Used to edit a SportsCentre Object with primary key given in url.

    Renders a form to the specified template_name on GET request.

    The Form will contain all the fields specified in the fields attribute.

    A POST request will save the  edit and redirect to success_url.
    """
    login_url = 'sports_centre:home'
    model = SportsCentre
    fields = ['name', 'description', 'address',
              'opening_time', 'closing_time', 'image']
    template_name = 'sports_centre/edit.html'
    success_url = reverse_lazy('sports_centre:home')

    def test_func(self):
        """
        Checks whether the user trying to access the url
        is the creator of the sports centre,if not redirect to login_url.
        """
        return self.request.user == self.get_object().creator


class DeleteGroundView(UserPassesTestMixin, DeleteView):
    """
    Used to delete a SportsCentre Object with primary key given in url.

    Renders a confirmation message to the specified template_name
    on GET request.

    A POST request will confirm deletion and redirect to success_url.
    """
    model = SportsCentre
    success_url = reverse_lazy('sports_centre:home')
    login_url = 'sports_centre:home'
    template_name = 'sports_centre/delete.html'
    context_object_name = 'sports_centre'

    def test_func(self):
        """
        Checks whether the user trying to access the url
        is the creator of the sports centre,if not redirect to login_url.
        """
        return self.request.user == self.get_object().creator


class HomeView(ListView):
    """
    Used to list all SportsCentre Objects.

    Passes all the objects as a list to template_name on GET request.
    """
    template_name = 'sports_centre/list.html'
    context_object_name = 'sports_centre_list'

    def get(self, request):
        """
        qry is the name of the search box used to search
        objects having name,description,address same as the
        value in search box.
        """
        sports_centre_list = SportsCentre.objects.all()
        query = request.GET.get("qry")
        if query:
            sports_centre_list = sports_centre_list.filter(
                                         Q(name__contains=query) |
                                         Q(description__contains=query) |
                                         Q(address__contains=query))

        return render(request, self.template_name,
                      {'sports_centre_list': sports_centre_list})


class SportsCentreDetailView(DetailView):
    """
    Show the detail page of the SportsCentre Object
    having primary key given in url.
    """
    model = SportsCentre
    template_name = 'sports_centre/detail.html'
    context_object_name = 'sports_centre'


class BookingView(View):
    """Booking page"""
    template_name = "sports_centre/booking.html"

    def get(self, request, pk):
        """
        Pass the primary key of the sports centre to
        be booked, so that time slots can be pre-populated.
        """
        form = BookingForm(pk)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        """
        Save the bookings in multiple rows for each time slot,
        then show success message in same page.
        """
        slot_list = request.POST.getlist('slot')
        name = request.POST['name']
        date = request.POST['date']
        phone_number = request.POST['phone_number']
        for timeslot in slot_list:
            booking = Booking(name=name, slot=timeslot, date=date,
                              phone_number=phone_number)
            booking.sports_centre = SportsCentre.objects.get(pk=pk)
            booking.save()
        success_message = ("Thank you " + name + " for booking " +
                           booking.sports_centre.name + " on " + date +
                           " for time slots:<br>")
        for t in slot_list:
            success_message += t+"<br>"
        messages.success(request, success_message)
        return HttpResponseRedirect(reverse_lazy('sports_centre:book',
                                                 args=(pk,)))


class BookingListing(UserPassesTestMixin, ListView):
    """Show all the bookings in the template specified in template_name."""
    template_name = 'sports_centre/bookinglist.html'
    context_object_name = 'booking_list'
    login_url = 'accounts:profile'

    def get_queryset(self):
        """Return all Bookings."""
        return Booking.objects.all().order_by('-date')

    def test_func(self):
        """
        Checks whether the user trying to access the url
        is a staff member,if not redirect to login_url.
        """
        return self.request.user.is_staff

sports_centre/templates/sports_centre/booking.html
{%extends "accounts/base.html"%}

{% block title_text%}Booking{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Booking</strong></h1></div>
				<div class="panel-body">
					<div class="form-group">
						{% if messages %}
						    {% for message in messages %}			    
						    	<div class="alert alert-success">
						    		<strong>
						    			{{ message|safe }}
						    		</strong>
						    	</div>		
						    {% endfor %}
						{% endif %}
					</div>
					<form method="post" id="bookingform" enctype="multipart/form-data">
						{% csrf_token %}			
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}
								<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}
						<input type="submit" id="bookbtn" class="btn btn-success" value="Save" />
					</form>					
				</div>
			</div>	
		</div>
	</div>
</div>
{%endblock%}

{% block js%}
<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
       rel = "stylesheet">
<script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
<script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script type="text/javascript" charset="utf-8" async defer>
$(function() {
  $( "#id_date" ).datepicker({dateFormat: "yy-mm-dd"});
  });
 

</script>
{%endblock%}

sports_centre/templates/sports_centre/bookinglist.html
{% extends "accounts/profile.html" %}
{% load el_pagination_tags %}
{% block title_text%}Booking-list{% endblock%}

{%block profilecontent%}

<h2><strong>List of Bookings</strong></h2>
<div class="table-responsive"> 
	<table class="table table-bordered table-responsive">
	    <thead style="background:#000; color:#fff;">
			<tr>
				<th>Name</th>
				<th>Sports Centre</th>
				<th>Phone Number</th>
				<th>Date</th>
				<th>Slot</th>
			</tr>
	    </thead>
	    <tbody>
	    	 {% paginate 10 booking_list %}   	
			{% for booking in booking_list %}			
				<tr>
					<td>{{booking.name}}</td>
					<td>{{booking.sports_centre}}</td>
					<td>{{booking.phone_number}}</td>
					<td>{{booking.date}}</td>
					<td>{{booking.slot}}</td>
				</tr>
			{%empty%}
				<tr>
					<td>No Data</td>
					<td>No Data</td>
					<td>No Data</td>
					<td>No Data</td>
					<td>No Data</td>        
				</tr>
			{%endfor%}
			{% get_pages %}			
	    </tbody>
	</table>
</div>
{% if pages.paginated %}
Pages:{{ pages.get_rendered }}    
{% endif %}

<br>
<br>
<a href="{% url 'accounts:profile' %}" class="btn btn-primary ">Back to Profile</a>
{%endblock%}

sports_centre/templates/sports_centre/create.html
{%extends "accounts/base.html"%}

{% block title_text%}Sports-Centre|Create{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Create Form</strong></h1></div>
				<div class="panel-body">
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}			
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}
								<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}
						<input type="submit" class="btn btn-success" value="Save" />
					</form>
				</div>
			</div>	
		</div>
	</div>
</div>
{%endblock%}

{%block js%}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script type="text/javascript" charset="utf-8" async defer>
$('#id_opening_time').timepicker({
    timeFormat: 'HH:mm',
    interval: 60,
    minTime: '1:00 am',
    maxTime: '23:00am',
    defaultTime: '6',
    startTime: '1:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
});
$('#id_closing_time').timepicker({
    timeFormat: 'HH:mm',
    interval: 60,
    minTime: '1:00 am',
    maxTime: '23:00am',
    defaultTime: '18',
    startTime: '1:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
});
</script>
{% endblock%}

sports_centre/templates/sports_centre/delete.html
{%extends "accounts/base.html"%}

{% block title_text%}Detail{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-12 ">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>{{sports_centre.name|title}}</strong></h1></div>
				<div class="panel-body">
					<div class="container-fluid">
						<div class="row">					
							<div class="col-lg-6 ">
								<img class="img-responsive" src="{{sports_centre.image.url}}" alt="">
								<br>			
								<div class="panel panel-success">
									<div class="panel-heading">Description</div>
									<div class="panel-body">
										
										<p>{{sports_centre.description}}</p>
									</div>
								</div>								
							</div>							
					     	<div class="col-lg-6   ">						
								<div class="panel panel-success">
									<div class="panel-heading">Timing</div>
									<div class="panel-body">	
										<p>{{sports_centre.opening_time}} to {{sports_centre.closing_time}}</p>
									</div>									
								</div>
								<div class="panel panel-success">
									<div class="panel-heading">Address</div>
									<div class="panel-body">	
										<p>{{sports_centre.address}}</p>
									</div>									
								</div>
								<form method="post">{% csrf_token %}
								    <p>Are you sure you want to delete "{{ object }}"?</p>
								    <input type="submit" class="btn btn-success btn-lg" value="Yes">
								    <br>
								    <br>
								    <a type="button" href="{% url 'sports_centre:detail' object.id %}" class="btn btn-danger form-control btn-lg">No</a>
								</form>
					     	</div>
					    </div>
				 	</div>
				</div>
			</div>	
		</div>
	</div>
</div>
<!--					-->	
{%endblock%}

sports_centre/templates/sports_centre/detail.html
{%extends "accounts/base.html"%}

{% block title_text%}Detail{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-12 ">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>{{sports_centre.name|title}}</strong></h1></div>
				<div class="panel-body">
					<div class="container-fluid">
						<div class="row">					
							<div class="col-lg-6 ">
								<img class="img-responsive" src="{{sports_centre.image.url}}" alt="">
								<br>			
								<div class="panel panel-success">
									<div class="panel-heading">Description</div>
									<div class="panel-body">
										
										<p>{{sports_centre.description}}</p>
									</div>
								</div>								
							</div>							
					     	<div class="col-lg-6   ">						
								<div class="panel panel-success">
									<div class="panel-heading">Timing</div>
									<div class="panel-body">	
										<p>{{sports_centre.opening_time}} to {{sports_centre.closing_time}}</p>
									</div>									
								</div>
								<div class="panel panel-success">
									<div class="panel-heading">Address</div>
									<div class="panel-body">	
										<p>{{sports_centre.address}}</p>
									</div>									
								</div>
								<a type="button" href="{% url 'sports_centre:book' object.id %}" class="btn btn-warning btn-lg">Make Booking</a>
								{% ifequal request.user  sports_centre.creator%}
								<a type="button" href="{% url 'sports_centre:edit' object.id %}" class="btn btn-primary btn-lg">Edit</a>
								<a type="button" href="{% url 'sports_centre:delete' object.id %}" class="btn btn-danger btn-lg">Delete</a>
								{%endifequal%}
					     	</div>
					    </div>
				 	</div>
				</div>
			</div>	
		</div>
	</div>
</div>
<!--					-->	
{%endblock%}

sports_centre/templates/sports_centre/edit.html
{%extends "accounts/base.html"%}

{% block title_text%}Sports-Centre|Edit{% endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-6 col-sm-offset-3">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>Edit Form</strong></h1></div>
				<div class="panel-body">
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}			
						{% for field in form %}
							<div class="form-group">
								{{ field.label_tag }}
								<br>
								{{ field }}
								<span class="helptext">{{field.help_text}}</span>
								<br>
							</div>
						{% endfor %}
						<input type="submit" class="btn btn-success" value="Save" />
					</form>
				</div>
			</div>	
		</div>
	</div>
</div>
{%endblock%}

{%block js%}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
<script type="text/javascript" charset="utf-8" async defer>
$('#id_opening_time').timepicker({
    timeFormat: 'HH:mm',
    interval: 60,
    minTime: '1:00 am',
    maxTime: '23:00am',
    defaultTime: '6',
    startTime: '1:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
});
$('#id_closing_time').timepicker({
    timeFormat: 'HH:mm',
    interval: 60,
    minTime: '1:00 am',
    maxTime: '23:00am',
    defaultTime: '18',
    startTime: '1:00',
    dynamic: true,
    dropdown: true,
    scrollbar: true
});
</script>
{% endblock%}

sports_centre/templates/sports_centre/list.html
{%extends "accounts/base.html"%}
{% load el_pagination_tags %}
{% block title_text%}Home{% endblock%}

{%block home_class%}active{%endblock%}

{%block searchbar%}
<li>
    <form class="navbar-form " action="" method="get">
        <div class="input-group">
            <input type="text" class="form-control"value="{{request.GET.qry}}" name="qry" placeholder="Search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
        </div>
    </form> 
</li>
{%endblock%}

{%block content%}
<div class="container" id="article">
	<div class="row">
		<br>
		<br>
		<div class="col-sm-12 ">
			<div class="panel panel-primary">
				<div class="panel-heading"><h1><strong>List of Sports Centres</strong></h1></div>
				<div class="panel-body">
					{% paginate 9 sports_centre_list %}
					<div class="row">
					{% for object in sports_centre_list %}
					<div class="col-lg-4 col-md-6 col-sm-12 portfolio-item">
						<div class="panel panel-success">
							<div class="panel-heading">
								<a href="{% url 'sports_centre:detail' object.id %}"><img class="img-responsive" src="{{object.image.url}}" alt=""></a>
							</div>
							<div class="panel-body">
								<h3><a href="{% url 'sports_centre:detail' object.id %}">{{object.name|title}}</a></h3>
								<p>{{object.address}}</p>		
							</div>
						</div>
			     	</div>
			     	{% empty %}
				     	<div class="jumbotron">
							<h1 class="text-danger">No Sports Centres found</h1>
				     	</div>
					{%endfor%}					
					{% get_pages %}
					</div>
					<br>
					{% if pages.paginated %}
					Pages:{{ pages.get_rendered }}    
					{% endif %}		
				</div>
			</div>	
		</div>
	</div>
</div>
{%endblock%}